// ── Subject categories ──────────────────────────────────────────────────────
export const SUBJECT_CATEGORY = {
  arithmetic:   "math",
  algebra:      "math",
  geometry:     "math",
  trigonometry: "math",
  calculus:     "math",
  statistics:   "math",
  wordproblems: "math",
  coding:       "cs",
  physics:      "science",
  chemistry:    "science",
  biology:      "science",
  history:      "humanities",
  geography:    "humanities",
  socialstudies:"humanities",
  economics:    "humanities",
  general:      "general",
};

export const SUBJECTS = {
  // ── Math ──
  arithmetic:   { label: "Arithmetic",    icon: "🔢", color: "#00ff87", desc: "Fractions, decimals, percentages", examples: ["What is ¾ + ⅔?", "Simplify 144 ÷ 12 × 3"] },
  algebra:      { label: "Algebra",       icon: "𝑥²", color: "#60a5fa", desc: "Equations, functions, polynomials", examples: ["Solve 2x² + 5x − 3 = 0", "Factor x² − 9"] },
  geometry:     { label: "Geometry",      icon: "△",  color: "#f59e0b", desc: "Shapes, area, volume, proofs",     examples: ["Area of a circle with r=7", "Find angles of a triangle"] },
  trigonometry: { label: "Trigonometry",  icon: "∠",  color: "#a78bfa", desc: "sin, cos, tan & identities",      examples: ["Solve sin(x) = √3/2", "Prove sin²x + cos²x = 1"] },
  calculus:     { label: "Calculus",      icon: "∫",  color: "#f97316", desc: "Derivatives, integrals, limits",  examples: ["Differentiate x³ + 2x²", "Integrate e^x · sin(x) dx"] },
  statistics:   { label: "Statistics",    icon: "📊", color: "#10b981", desc: "Probability & data analysis",     examples: ["Explain standard deviation", "What is a p-value?"] },
  wordproblems: { label: "Word Problems", icon: "📝", color: "#ec4899", desc: "Real-world applied math",         examples: ["A train leaves at 60 mph...", "3 workers finish a wall in 4 days..."] },
  // ── CS ──
  coding:       { label: "Coding & CS",   icon: "💻", color: "#22d3ee", desc: "Programming, DSA, algorithms",   examples: ["Write a binary search in Python", "Explain Big O notation", "How does recursion work?"] },
  // ── Science ──
  physics:      { label: "Physics",       icon: "⚛️", color: "#fb923c", desc: "Mechanics, waves, electricity",  examples: ["F = ma explained", "Calculate kinetic energy at 20 m/s", "Ohm's law circuit problem"] },
  chemistry:    { label: "Chemistry",     icon: "🧪", color: "#4ade80", desc: "Reactions, bonding, stoichiometry", examples: ["Balance: H₂ + O₂ → H₂O", "Explain ionic vs covalent bonds", "Mole calculation for NaCl"] },
  biology:      { label: "Biology",       icon: "🧬", color: "#f472b6", desc: "Cells, genetics, evolution",     examples: ["Explain DNA replication", "How does mitosis work?", "What is natural selection?"] },
  // ── Humanities ──
  history:      { label: "History",       icon: "🏛️", color: "#c084fc", desc: "World & Indian history, events",  examples: ["Causes of World War 1", "Explain the French Revolution", "Mughal Empire overview"] },
  geography:    { label: "Geography",     icon: "🌍", color: "#34d399", desc: "Physical & human geography",     examples: ["Explain the water cycle", "Types of rocks explained", "Monsoon in India"] },
  socialstudies:{ label: "Social Studies",icon: "📜", color: "#fbbf24", desc: "Civics, polity, society",        examples: ["How does Indian Parliament work?", "Fundamental rights explained", "UN and its agencies"] },
  economics:    { label: "Economics",     icon: "📈", color: "#f87171", desc: "Macro & microeconomics",         examples: ["Law of demand explained", "What is GDP?", "Inflation causes and effects"] },
  // ── General ──
  general:      { label: "Any Topic",     icon: "🎓", color: "#94a3b8", desc: "Mixed topics or not sure",       examples: ["Explain the Pythagorean theorem", "Help me understand logarithms"] },
};

export const BOARDS = {
  general:  { label: "General",         grades: [],                         color: "#94a3b8", icon: "📚" },
  CBSE:     { label: "CBSE",            grades: ["6","7","8","9","10","11","12"], color: "#00ff87", icon: "🎓" },
  ICSE:     { label: "ICSE / ISC",      grades: ["8","9","10","11","12"],    color: "#60a5fa", icon: "📘" },
  WBSSE:    { label: "WB Board",        grades: ["9","10","11","12"],        color: "#f59e0b", icon: "📗" },
  STATE:    { label: "State Board",     grades: ["8","9","10","11","12"],    color: "#a78bfa", icon: "🏫" },
  JEE:      { label: "JEE Main/Adv",   grades: ["11","12","Dropper"],       color: "#f97316", icon: "⚡" },
  NEET:     { label: "NEET",            grades: ["11","12","Dropper"],       color: "#ec4899", icon: "🔬" },
  UNDERGRAD:{ label: "Undergraduate",   grades: ["1st yr","2nd yr","3rd yr","4th yr"], color: "#10b981", icon: "🎯" },
};

export const LANG_NAMES = { hi: "Hindi", bn: "Bengali", en: "English" };

export const LANGS = {
  en: { label: "En", full: "English", voice: "en-IN" },
  hi: { label: "Hi", full: "हिंदी",   voice: "hi-IN" },
  bn: { label: "Bn", full: "বাংলা",   voice: "bn-IN" },
};

export const UI = {
  en: {
    tagline: "Free · No account · Powered by local AI",
    heroTitle: ["Your personal", "AI tutor"],
    heroSub: "Step-by-step solutions across math, coding, and science. Type, speak, or photo your problem.",
    teachingStyle: "Teaching Style",
    chooseSubject: "Choose a Subject",
    selectBoard: "Select Board",
    selectGrade: "Grade",
    startChat: "Start Chatting →",
    newChat: "+ New Chat",
    history: "History",
    noHistory: "No saved chats yet.",
    clearHistory: "Clear all history",
    send: "Send",
    photo: "Photo",
    speak: "Speak",
    stop: "Stop",
    copy: "copy",
    copied: "✓ copied",
    topic: "TOPIC",
    viewVisual: "View Visual",
    chatHistory: "Chat History",
    hint: "Type your question...",
    cached: "⚡ instant",
    talkBtn: "💬 Talk to TAKSHA",
    listening: "Listening — speak now...",
    boardBtn: "Board",
    clearInput: "clear",
    showReasoning: "Show reasoning",
    hideReasoning: "Hide reasoning",
    verified: "✓ verified",
    talkHint: "Say something...",
    talkFooter: "Enter to send · Shift+Enter for newline",
    searchChats: "Search chats...",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    older: "Older",
    queueWait: "in queue — waiting for GPU...",
    retry: "↻ Retry",
    mock: {
      subject: "📐 Geometry",
      question: "Explain the Pythagorean theorem",
      method: "Pythagorean Theorem",
      step: () => `In a right triangle, the square of the hypotenuse equals the sum of squares of the other two sides.`,
      formula: "a² + b² = c²",
      result: "where c is the hypotenuse",
      or: "or",
      placeholder: "Ask a math question...",
    },
    ob: {
      title: "👋 Quick setup",
      subtitle: "Helps Taksha give you better answers",
      name: "Your name (optional)",
      namePlaceholder: "e.g. Rahul",
      classYear: "Class / Year",
      boardExam: "Board / Exam",
      helpWith: "I mainly need help with",
      letsGo: "Let's go →",
      letsGoName: (n) => `Let's go, ${n} →`,
      skip: "skip",
    },
    welcome: (s) => `Hey! Ready to help with ${s}. Drop your problem — type it, snap a photo, or speak it.`,
    categories: { math: "Mathematics", cs: "Computer Science", science: "Sciences", humanities: "Humanities & Social Studies", general: "General" },
    topics: {
      arithmetic:   { label: "Arithmetic",    desc: "Fractions, decimals, percentages" },
      algebra:      { label: "Algebra",        desc: "Equations, functions, polynomials" },
      geometry:     { label: "Geometry",       desc: "Shapes, area, volume, proofs" },
      trigonometry: { label: "Trigonometry",   desc: "sin, cos, tan & identities" },
      calculus:     { label: "Calculus",       desc: "Derivatives, integrals, limits" },
      statistics:   { label: "Statistics",     desc: "Probability & data analysis" },
      wordproblems: { label: "Word Problems",  desc: "Real-world applied math" },
      coding:       { label: "Coding & CS",    desc: "Programming, DSA, algorithms" },
      physics:      { label: "Physics",        desc: "Mechanics, waves, electricity" },
      chemistry:    { label: "Chemistry",      desc: "Reactions, bonding, stoichiometry" },
      biology:      { label: "Biology",        desc: "Cells, genetics, evolution" },
      history:      { label: "History",        desc: "World & Indian history, events" },
      geography:    { label: "Geography",      desc: "Physical & human geography" },
      socialstudies:{ label: "Social Studies", desc: "Civics, polity, society" },
      economics:    { label: "Economics",      desc: "Macro & microeconomics" },
      general:      { label: "Any Topic",      desc: "Mixed topics or not sure" },
    },
    styles: {
      stepbystep:     { label: "Step-by-Step", desc: "Numbered, explicit steps" },
      conversational: { label: "Friendly",     desc: "Warm & relatable" },
      socratic:       { label: "Socratic",     desc: "Guided discovery" },
    },
  },
  hi: {
    tagline: "मुफ़्त · कोई खाता नहीं · लोकल AI",
    heroTitle: ["आपका निजी", "AI शिक्षक"],
    heroSub: "गणित, कोडिंग और विज्ञान में हर कदम की पूरी व्याख्या। टाइप करें, बोलें, या फ़ोटो लें।",
    teachingStyle: "पढ़ाने का तरीका",
    chooseSubject: "विषय चुनें",
    selectBoard: "बोर्ड चुनें",
    selectGrade: "कक्षा",
    startChat: "शुरू करें →",
    newChat: "+ नई बात",
    history: "इतिहास",
    noHistory: "अभी तक कोई चैट नहीं।",
    clearHistory: "सभी इतिहास हटाएं",
    send: "भेजें",
    photo: "फ़ोटो",
    speak: "बोलें",
    stop: "रोकें",
    copy: "कॉपी",
    copied: "✓ कॉपी",
    topic: "विषय",
    viewVisual: "चित्र देखें",
    chatHistory: "चैट इतिहास",
    hint: "अपना सवाल लिखें...",
    cached: "⚡ तत्काल",
    talkBtn: "💬 Taksha से बात करें",
    listening: "सुन रहा हूं — अभी बोलें...",
    boardBtn: "बोर्ड",
    clearInput: "साफ़",
    showReasoning: "सोच दिखाएं",
    hideReasoning: "सोच छुपाएं",
    verified: "✓ जांचा गया",
    talkHint: "कुछ कहें...",
    talkFooter: "Enter भेजें · Shift+Enter नई लाइन",
    searchChats: "चैट खोजें...",
    today: "आज",
    yesterday: "कल",
    thisWeek: "इस सप्ताह",
    older: "पुराने",
    queueWait: "कतार में — GPU का इंतज़ार...",
    retry: "↻ फिर कोशिश करें",
    mock: {
      subject: "📐 ज्यामिति",
      question: "पाइथागोरस प्रमेय समझाएं",
      method: "पाइथागोरस प्रमेय",
      step: () => `एक समकोण त्रिभुज में, कर्ण का वर्ग अन्य दो भुजाओं के वर्गों के योग के बराबर होता है।`,
      formula: "a² + b² = c²",
      result: "जहाँ c कर्ण है",
      or: "या",
      placeholder: "गणित का सवाल पूछें...",
    },
    ob: {
      title: "👋 त्वरित सेटअप",
      subtitle: "Taksha को बेहतर उत्तर देने में मदद करता है",
      name: "आपका नाम (वैकल्पिक)",
      namePlaceholder: "जैसे राहुल",
      classYear: "कक्षा / वर्ष",
      boardExam: "बोर्ड / परीक्षा",
      helpWith: "मुझे मुख्यतः मदद चाहिए",
      letsGo: "चलो शुरू करें →",
      letsGoName: (n) => `चलो, ${n} →`,
      skip: "छोड़ें",
    },
    welcome: (s) => `नमस्ते! ${s} में मदद करने के लिए तैयार हूं। अपना सवाल टाइप करें, फ़ोटो लें, या बोलें।`,
    categories: { math: "गणित", cs: "कंप्यूटर विज्ञान", science: "विज्ञान", humanities: "मानविकी और सामाजिक अध्ययन", general: "सामान्य" },
    topics: {
      arithmetic:   { label: "अंकगणित",      desc: "भिन्न, दशमलव, प्रतिशत" },
      algebra:      { label: "बीजगणित",       desc: "समीकरण, फलन, बहुपद" },
      geometry:     { label: "ज्यामिति",      desc: "आकार, क्षेत्रफल, आयतन, प्रमाण" },
      trigonometry: { label: "त्रिकोणमिति",   desc: "sin, cos, tan और सूत्र" },
      calculus:     { label: "कलनशास्त्र",    desc: "अवकलन, समाकलन, सीमाएं" },
      statistics:   { label: "सांख्यिकी",     desc: "प्रायिकता और डेटा विश्लेषण" },
      wordproblems: { label: "शब्द समस्याएं", desc: "वास्तविक जीवन की गणित" },
      coding:       { label: "कोडिंग व CS",   desc: "प्रोग्रामिंग, DSA, एल्गोरिदम" },
      physics:      { label: "भौतिकी",        desc: "यांत्रिकी, तरंगें, विद्युत" },
      chemistry:    { label: "रसायन विज्ञान", desc: "अभिक्रियाएं, बंधन, स्टोइकियोमेट्री" },
      biology:      { label: "जीव विज्ञान",   desc: "कोशिकाएं, आनुवंशिकी, विकास" },
      history:      { label: "इतिहास",        desc: "विश्व और भारतीय इतिहास" },
      geography:    { label: "भूगोल",         desc: "भौतिक और मानव भूगोल" },
      socialstudies:{ label: "सामाजिक अध्ययन",desc: "नागरिकशास्त्र, राजनीति, समाज" },
      economics:    { label: "अर्थशास्त्र",   desc: "समष्टि और व्यष्टि अर्थशास्त्र" },
      general:      { label: "कोई भी विषय",   desc: "मिश्रित या अनिश्चित विषय", examples: ["पाइथागोरस प्रमेय समझाएं", "लघुगणक क्या होता है?"] },
      algebra:      { label: "बीजगणित",       examples: ["2x² + 5x − 3 = 0 हल करें", "x² − 9 के गुणनखंड निकालें"] },
      geometry:     { label: "ज्यामिति",      examples: ["r=7 वाले वृत्त का क्षेत्रफल", "त्रिभुज के कोण ज्ञात करें"] },
      history:      { label: "इतिहास",        examples: ["प्रथम विश्व युद्ध के कारण", "मुगल साम्राज्य का परिचय"] },
      economics:    { label: "अर्थशास्त्र",   examples: ["मांग का नियम क्या है?", "GDP क्या होता है?"] },
    },
    styles: {
      stepbystep:     { label: "चरण-दर-चरण", desc: "क्रमबद्ध, स्पष्ट कदम" },
      conversational: { label: "मित्रवत",    desc: "सरल और आकर्षक" },
      socratic:       { label: "सुकराती",    desc: "प्रश्नों से सीखें" },
    },
  },
  bn: {
    tagline: "বিনামূল্যে · অ্যাকাউন্ট নেই · লোকাল AI",
    heroTitle: ["আপনার ব্যক্তিগত", "AI শিক্ষক"],
    heroSub: "গণিত, কোডিং ও বিজ্ঞানে প্রতিটি ধাপের সম্পূর্ণ ব্যাখ্যা। টাইপ করুন, বলুন বা ছবি তুলুন।",
    teachingStyle: "পড়ানোর ধরন",
    chooseSubject: "বিষয় বেছে নিন",
    selectBoard: "বোর্ড বেছে নিন",
    selectGrade: "শ্রেণী",
    startChat: "শুরু করুন →",
    newChat: "+ নতুন চ্যাট",
    history: "ইতিহাস",
    noHistory: "এখনো কোনো চ্যাট নেই।",
    clearHistory: "সব ইতিহাস মুছুন",
    send: "পাঠান",
    photo: "ছবি",
    speak: "বলুন",
    stop: "থামুন",
    copy: "কপি",
    copied: "✓ কপি",
    topic: "বিষয়",
    viewVisual: "চিত্র দেখুন",
    chatHistory: "চ্যাট ইতিহাস",
    hint: "আপনার প্রশ্ন লিখুন...",
    cached: "⚡ তাৎক্ষণিক",
    talkBtn: "💬 Taksha-র সাথে কথা বলুন",
    listening: "শুনছি — এখন বলুন...",
    boardBtn: "বোর্ড",
    clearInput: "মুছুন",
    showReasoning: "চিন্তা দেখুন",
    hideReasoning: "চিন্তা লুকান",
    verified: "✓ যাচাই হয়েছে",
    talkHint: "কিছু বলুন...",
    talkFooter: "Enter পাঠান · Shift+Enter নতুন লাইন",
    searchChats: "চ্যাট খুঁজুন...",
    today: "আজ",
    yesterday: "গতকাল",
    thisWeek: "এই সপ্তাহ",
    older: "পুরনো",
    queueWait: "সারিতে — GPU-র জন্য অপেক্ষা...",
    retry: "↻ আবার চেষ্টা করুন",
    mock: {
      subject: "📐 জ্যামিতি",
      question: "পিথাগোরাস উপপাদ্য ব্যাখ্যা করুন",
      method: "পিথাগোরাস উপপাদ্য",
      step: () => `একটি সমকোণী ত্রিভুজে অতিভুজের বর্গ অপর দুই বাহুর বর্গের যোগফলের সমান।`,
      formula: "a² + b² = c²",
      result: "যেখানে c হলো অতিভুজ",
      or: "অথবা",
      placeholder: "গণিতের প্রশ্ন করুন...",
    },
    ob: {
      title: "👋 দ্রুত সেটআপ",
      subtitle: "Taksha-কে ভালো উত্তর দিতে সাহায্য করে",
      name: "আপনার নাম (ঐচ্ছিক)",
      namePlaceholder: "যেমন রাহুল",
      classYear: "শ্রেণী / বর্ষ",
      boardExam: "বোর্ড / পরীক্ষা",
      helpWith: "আমার প্রধানত সাহায্য দরকার",
      letsGo: "শুরু করা যাক →",
      letsGoName: (n) => `চলো, ${n} →`,
      skip: "এড়িয়ে যান",
    },
    welcome: (s) => `নমস্কার! ${s}-এ সাহায্য করতে প্রস্তুত। টাইপ করুন, ছবি তুলুন বা বলুন।`,
    categories: { math: "গণিত", cs: "কম্পিউটার বিজ্ঞান", science: "বিজ্ঞান", humanities: "মানবিক ও সমাজবিজ্ঞান", general: "সাধারণ" },
    topics: {
      arithmetic:   { label: "পাটিগণিত",       desc: "ভগ্নাংশ, দশমিক, শতাংশ" },
      algebra:      { label: "বীজগণিত",        desc: "সমীকরণ, ফাংশন, বহুপদী" },
      geometry:     { label: "জ্যামিতি",       desc: "আকার, ক্ষেত্রফল, আয়তন, প্রমাণ" },
      trigonometry: { label: "ত্রিকোণমিতি",    desc: "sin, cos, tan ও সূত্র" },
      calculus:     { label: "ক্যালকুলাস",     desc: "অবকলন, সমাকলন, সীমা" },
      statistics:   { label: "পরিসংখ্যান",     desc: "সম্ভাবনা ও তথ্য বিশ্লেষণ" },
      wordproblems: { label: "শব্দ সমস্যা",    desc: "বাস্তব জীবনের গণিত" },
      coding:       { label: "কোডিং ও CS",     desc: "প্রোগ্রামিং, DSA, অ্যালগরিদম" },
      physics:      { label: "পদার্থবিজ্ঞান",  desc: "বলবিদ্যা, তরঙ্গ, বিদ্যুৎ" },
      chemistry:    { label: "রসায়নবিজ্ঞান",  desc: "বিক্রিয়া, বন্ধন, স্টোইকিওমেট্রি" },
      biology:      { label: "জীববিজ্ঞান",     desc: "কোষ, জিনতত্ত্ব, বিবর্তন" },
      history:      { label: "ইতিহাস",         desc: "বিশ্ব ও ভারতীয় ইতিহাস" },
      geography:    { label: "ভূগোল",          desc: "ভৌত ও মানব ভূগোল" },
      socialstudies:{ label: "সমাজবিজ্ঞান",   desc: "পৌরনীতি, রাজনীতি, সমাজ" },
      economics:    { label: "অর্থনীতি",       desc: "সামষ্টিক ও ব্যষ্টিক অর্থনীতি" },
      general:      { label: "যেকোনো বিষয়",   desc: "মিশ্র বা অনিশ্চিত বিষয়", examples: ["পিথাগোরাস উপপাদ্য ব্যাখ্যা করুন", "লগারিদম কী?"] },
      algebra:      { label: "বীজগণিত",        examples: ["2x² + 5x − 3 = 0 সমাধান করুন", "x² − 9 উৎপাদকে বিশ্লেষণ করুন"] },
      geometry:     { label: "জ্যামিতি",       examples: ["r=7 বৃত্তের ক্ষেত্রফল", "ত্রিভুজের কোণ নির্ণয় করুন"] },
      history:      { label: "ইতিহাস",         examples: ["প্রথম বিশ্বযুদ্ধের কারণ", "মুঘল সাম্রাজ্যের পরিচয়"] },
      economics:    { label: "অর্থনীতি",       examples: ["চাহিদার সূত্র কী?", "GDP কী?"] },
    },
    styles: {
      stepbystep:     { label: "ধাপে ধাপে",      desc: "ক্রমানুসারে স্পষ্ট পদক্ষেপ" },
      conversational: { label: "বন্ধুত্বপূর্ণ",  desc: "সহজ ও আকর্ষণীয়" },
      socratic:       { label: "সক্রেটিক",       desc: "প্রশ্নের মাধ্যমে শিখুন" },
    },
  },
};
